sudo: required
services:
  - docker

before_install:
  - docker build -t ondaesuk93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ondaesuk93/react-test npm test -- --coverage

after_success:
  - docker build -t ondaesuk93/multi-client ./client
  - docker build -t ondaesuk93/multi-nginx ./nginx
  - docker build -t ondaesuk93/multi-server ./server
  # - docker build -t ondaesuk93/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ondaesuk93/multi-client
  - docker push ondaesuk93/multi-nginx
  - docker push ondaesuk93/multi-server
  # - docker push ondaesuk93/multi-worker