#1
sudo: required
#2
services:
- docker
#3
before_install:
- docker build -t onsuk/docker-travis-practice -f Dockerfile.dev .
#4
script:
- docker run onsuk/docker-travis-practice npm run test -- --coverage