#1
sudo: required
#2
services:
- docker
#3
before_install:
- docker build -t /Users/onz/docker-exam-react -f Dockerfile.dev .
#4
script:
- docker run /Users/onz/docker-exam-react npm run test -- --coverage